# Generated by Django 5.0.6 on 2024-06-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('purpose', models.CharField(max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '2. Donor List',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(choices=[('DR', 'Dr.'), ('MR', 'Mr.')], default='Dr.', max_length=2)),
                ('full_name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=30, null=True, unique=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('office_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('other_location', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=15, null=True)),
                ('state', models.CharField(choices=[('TX', 'Texas')], default='Texas', max_length=20)),
                ('zip_code', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(choices=[('US', 'United States')], default='United States', max_length=20)),
                ('medical', models.CharField(choices=[('DMC', 'Dow Medical College'), ('SMC', 'Sindh Medical College'), ('AKMC', 'Aga Khan Medical College'), ('BMC', 'Bolan Medical College'), ('KMDC', 'Karachi Medical and Dental College'), ('ZMC', 'Ziauddin Medical College'), ('JMC', 'Jamshoro Medical College'), ('KEMC', 'King Edward Medical College'), ('AIMC', 'Allama Iqbal Medical College'), ('FJMC', 'Fatima Jinnah Medical College'), ('RMC', 'Rawalpindi Medical College'), ('NMC', 'Nishtar Medical College'), ('AMC', 'Ayub Medical College'), ('Others', 'Others')], max_length=20, null=True)),
                ('year_of_graduation', models.CharField(max_length=15, null=True)),
                ('membership_type', models.CharField(choices=[('LM', 'Lifetime Member ($100)')], default='Lifetime Member ($100)', max_length=20)),
                ('profile_photo', models.ImageField(blank=True, default='profile-pic.jpg', null=True, upload_to='member')),
                ('license', models.ImageField(blank=True, null=True, upload_to='member/license')),
                ('password', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '1. Member List',
                'ordering': ['-created_at'],
            },
        ),
    ]
