# Generated by Django 5.0.6 on 2024-06-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-id'], 'verbose_name': '2. Donor List'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-id'], 'verbose_name': '1. Member List'},
        ),
        migrations.RenameField(
            model_name='member',
            old_name='created_at',
            new_name='member_from',
        ),
    ]
