# Generated by Django 5.0.6 on 2024-05-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_member_alter_donation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(default='Houston', max_length=15),
        ),
        migrations.AddField(
            model_name='member',
            name='country',
            field=models.CharField(choices=[('US', 'United States')], default='United States', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='home_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='medical',
            field=models.CharField(choices=[('DMC', 'Dow Medical College'), ('SMC', 'Sindh Medical College')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('LM', 'Lifetime Member ($100)')], default='Lifetime Member ($100)', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='office_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='other_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='state',
            field=models.CharField(choices=[('TX', 'Texas')], default='Texas', max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='year_of_graduation',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='zip_code',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
