# Generated by Django 5.0.6 on 2024-05-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_member_city_member_country_member_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='last_name',
        ),
        migrations.AddField(
            model_name='donation',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='purpose',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='city',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
