# Generated by Django 5.0.6 on 2024-06-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_donation_first_name_remove_donation_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='member',
            name='Full_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
