# Generated by Django 5.0.6 on 2024-06-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_member_first_name_remove_member_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Full_name',
            new_name='full_name',
        ),
    ]
