# Generated by Django 5.0.6 on 2024-06-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_member_city_alter_member_home_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': '2. Donor List'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '1. Member List'},
        ),
        migrations.AddField(
            model_name='member',
            name='license',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile-pic.jpg', null=True, upload_to=''),
        ),
    ]
