# Generated by Django 5.0.6 on 2024-06-04 17:15

import prefix_id.field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_member_password_alter_member_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id',
            field=prefix_id.field.PrefixIDField(editable=False, max_length=27, prefix='book', primary_key=True, serialize=False, unique=True),
        ),
    ]
