# Generated by Django 5.0.6 on 2024-06-04 17:18

import prefix_id.field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='id',
            field=prefix_id.field.PrefixIDField(editable=False, max_length=27, prefix='APP1', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=prefix_id.field.PrefixIDField(editable=False, max_length=27, prefix='APP1', primary_key=True, serialize=False, unique=True),
        ),
    ]
